### ISSUE TITLE
Why is Titanium SDK dependent on Nodejs

### ISSUE THREAD

**Issue by allcpu** [tidev/titanium-sdk#13962]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

I was trying using Titanium SDK but when I found that it is totally dependent on the nodejs to make apps I was not able to use it as the Titanium SdK requirements are fulfilled but not Nodejs.
Even Android SDK and NDK are compatible with the olderversion of PC but this Nodejs is not.

### Solution

We should try to seprate the Nodejs and Titanium as Titanium don't require it and only its CLI need it.
For the use of CLI many indie developers like me are unable to use this precious SDK.

### Alternatives

A new Fork of this SDK be made which is Independent of Nodejs and Is provided as Installer or as Portable format

### Platforms

Android, iOS, CLI

**Comment by m1ga** [comment]
>  and only its CLI need it

The CLI is Javascript based so you'll need a Javascript runtime on your machine to use it. That is what Node.js is doing here. So in order to remove Node.js from Ti you have to rewrite everything in a different runtime. But that just means you have to install that runtime.

So I don't see that happening at any time as Node.js is a very common and well supported JS runtime. If there even was a switch I'm sure it will be to a new runtime like Bun or Deno and I'm sure they don't support old PC. Going to something like Java or native EXE files would require to have dedicated developers for each platform. And since it's an open-source project there is not the manpower to do that. And it wouldn't be the right way to do it anyways

**Comment by cb1kenobi** [comment]
How old of a PC are we talking? Windows 95?

**Comment by allcpu** [comment]
I am not only commenting about pc but also android which is not supported due to the nodejs or someone should implement a free online platform for such devices.

**Comment by m1ga** [comment]
but then you have to ask the node.js people to support older versions. We just use their tool and at some point we have to stop supporting old versions and use the latest because of security issues and new features. 

As a workaround you could even install Linux (I'm running Fedora as my main machine) which can build Android versions without an issue if you can't update your Windows version. You have to use a Mac anyways to build for iOS

**Comment by m1ga** [comment]
I'll close this for now as we don't have any manpower or interest in removing nodejs at the moment. It's the same as with any other software: old hard/software will be out of date at some point. Especially if it is an external tool that we can't control

**Comment by hbugdoll** [comment]
Because _IOS_ was explicitly mentioned above, I would like to show the following cascade to illustrate the minimum iOS requirements.

In case of an app published in the App Store 2024:
min. target iOS 17 &larr; Xcode 15.0 &larr; macOS Ventura &larr; an Apple computer from 2017/18 ("&larr;" means "_requires at least_")

----

I suspect that the issue creator was bothered by the Windows minimum requirements for node.js (min. Windows 10).
The ext. support of Windows 8.1 ends in 2023.

ChatGPT lists the following main reasons why an SDK such as Titanium SDK should only support operating systems that still receive updates from their vendors:
1. Security
2. Debuggability & Maintainability
3. Toolchain & Compatibility
4. Resource Focus
5. Liability and Responsibility
